### ISSUE TITLE
Action Failure due to Errors

### ISSUE THREAD

**Issue by fangmarks** [Nuytemans-Dieter/YAML-sync-action#1]
I'm currently trying to use this Action to automatically generate Language files for my Discord Bot, but for some reason your Action is throwing Errors, which causes my Build to fail

![](https://e-six-two.one/i/ra5c.png)

**Comment by Nuytemans-Dieter** [comment]
Sorry for seeing this so late, I was on a holiday. Thank you for reporting an issue, this action never fully worked but another one of my repos does work well.
So I suggest using [this repo](https://github.com/Nuytemans-Dieter/YAML-localisation-sync). It contains the same functionality but only requires a bit more copy/pasting.
